// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Premag.Infrastructure.Data;

#nullable disable

namespace Premag.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Premag.Core.Entities.Apontamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<Guid?>("AlteradoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("alterado_por_id");

                    b.Property<Guid>("ClienteUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_uuid");

                    b.Property<Guid>("ColaboradorId")
                        .HasColumnType("uuid")
                        .HasColumnName("colaborador_id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("CriadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por_id");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<string>("DispositivoId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("dispositivo_id");

                    b.Property<bool>("Excluido")
                        .HasColumnType("boolean")
                        .HasColumnName("excluido");

                    b.Property<Guid>("FrenteId")
                        .HasColumnType("uuid")
                        .HasColumnName("frente_id");

                    b.Property<TimeOnly?>("HoraFim")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_fim");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_inicio");

                    b.Property<bool>("JornadaNaoVerificada")
                        .HasColumnType("boolean")
                        .HasColumnName("jornada_nao_verificada");

                    b.Property<int?>("MinutosEfetivos")
                        .HasColumnType("integer")
                        .HasColumnName("minutos_efetivos");

                    b.Property<Guid?>("MotivoParadaId")
                        .HasColumnType("uuid")
                        .HasColumnName("motivo_parada_id");

                    b.Property<string>("Observacao")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("observacao");

                    b.Property<short>("Origem")
                        .HasColumnType("smallint")
                        .HasColumnName("origem");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_apontamentos");

                    b.HasIndex("AlteradoPorId")
                        .HasDatabaseName("ix_apontamentos_alterado_por_id");

                    b.HasIndex("ColaboradorId")
                        .HasDatabaseName("ix_apontamentos_colaborador_id");

                    b.HasIndex("CriadoPorId")
                        .HasDatabaseName("ix_apontamentos_criado_por_id");

                    b.HasIndex("FrenteId")
                        .HasDatabaseName("ix_apontamentos_frente_id");

                    b.HasIndex("MotivoParadaId")
                        .HasDatabaseName("ix_apontamentos_motivo_parada_id");

                    b.HasIndex("TenantId", "ClienteUuid")
                        .IsUnique()
                        .HasDatabaseName("ix_apontamentos_tenant_id_cliente_uuid");

                    b.HasIndex("TenantId", "ColaboradorId")
                        .IsUnique()
                        .HasDatabaseName("ix_apontamentos_aberto_por_colaborador")
                        .HasFilter("hora_fim IS NULL AND excluido = FALSE");

                    b.HasIndex("TenantId", "ColaboradorId", "Data")
                        .HasDatabaseName("ix_apontamentos_tenant_id_colaborador_id_data");

                    b.HasIndex("TenantId", "FrenteId", "Data")
                        .HasDatabaseName("ix_apontamentos_tenant_id_frente_id_data");

                    b.ToTable("apontamentos", (string)null);
                });

            modelBuilder.Entity("Premag.Core.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("acao");

                    b.Property<string>("Antes")
                        .HasColumnType("jsonb")
                        .HasColumnName("antes");

                    b.Property<string>("Depois")
                        .HasColumnType("jsonb")
                        .HasColumnName("depois");

                    b.Property<DateTimeOffset>("Em")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("em");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("entidade");

                    b.Property<Guid>("EntidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("entidade_id");

                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("TenantId", "Entidade", "EntidadeId")
                        .HasDatabaseName("ix_audit_logs_tenant_id_entidade_entidade_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Premag.Core.Entities.Colaborador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("CodigoExterno")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("codigo_externo");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<decimal?>("CustoHora")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("custo_hora");

                    b.Property<DateOnly?>("DataAdmissao")
                        .HasColumnType("date")
                        .HasColumnName("data_admissao");

                    b.Property<Guid>("EquipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipe_id");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("funcao");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("matricula");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<short>("OrigemCadastro")
                        .HasColumnType("smallint")
                        .HasColumnName("origem_cadastro");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_colaboradores");

                    b.HasIndex("EquipeId")
                        .HasDatabaseName("ix_colaboradores_equipe_id");

                    b.HasIndex("TenantId", "Matricula")
                        .IsUnique()
                        .HasDatabaseName("ix_colaboradores_tenant_id_matricula");

                    b.ToTable("colaboradores", (string)null);
                });

            modelBuilder.Entity("Premag.Core.Entities.Configuracao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DiasFechamento")
                        .HasColumnType("integer")
                        .HasColumnName("dias_fechamento");

                    b.Property<TimeOnly>("IntervaloFim")
                        .HasColumnType("time without time zone")
                        .HasColumnName("intervalo_fim");

                    b.Property<TimeOnly>("IntervaloInicio")
                        .HasColumnType("time without time zone")
                        .HasColumnName("intervalo_inicio");

                    b.Property<TimeOnly>("JornadaFim")
                        .HasColumnType("time without time zone")
                        .HasColumnName("jornada_fim");

                    b.Property<TimeOnly>("JornadaInicio")
                        .HasColumnType("time without time zone")
                        .HasColumnName("jornada_inicio");

                    b.Property<int>("JornadaPadraoMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("jornada_padrao_minutos");

                    b.Property<int>("MinutosOciosidadeEscalonamento")
                        .HasColumnType("integer")
                        .HasColumnName("minutos_ociosidade_escalonamento");

                    b.Property<int>("MinutosSemServico")
                        .HasColumnType("integer")
                        .HasColumnName("minutos_sem_servico");

                    b.Property<int>("MinutosServicoAbertoDemais")
                        .HasColumnType("integer")
                        .HasColumnName("minutos_servico_aberto_demais");

                    b.Property<int>("RetencaoFotosMeses")
                        .HasColumnType("integer")
                        .HasColumnName("retencao_fotos_meses");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_configuracoes");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_configuracoes_tenant_id");

                    b.ToTable("configuracoes", (string)null);
                });

            modelBuilder.Entity("Premag.Core.Entities.Equipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ativa");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("cor");

                    b.Property<Guid?>("EncarregadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("encarregado_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("nome");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_equipes");

                    b.HasIndex("EncarregadoId")
                        .HasDatabaseName("ix_equipes_encarregado_id");

                    b.HasIndex("TenantId", "Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_equipes_tenant_id_nome");

                    b.ToTable("equipes", (string)null);
                });

            modelBuilder.Entity("Premag.Core.Entities.Etapa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Indireta")
                        .HasColumnType("boolean")
                        .HasColumnName("indireta");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nome");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_etapas");

                    b.HasIndex("TenantId", "Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_etapas_tenant_id_nome");

                    b.ToTable("etapas", (string)null);
                });

            modelBuilder.Entity("Premag.Core.Entities.FechamentoDia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<Guid?>("EquipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipe_id");

                    b.Property<DateTimeOffset>("FechadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechado_em");

                    b.Property<Guid>("FechadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("fechado_por_id");

                    b.Property<string>("MotivoReabertura")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("motivo_reabertura");

                    b.Property<DateTimeOffset?>("ReabertoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reaberto_em");

                    b.Property<Guid?>("ReabertoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("reaberto_por_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_fechamentos_dia");

                    b.HasIndex("EquipeId")
                        .HasDatabaseName("ix_fechamentos_dia_equipe_id");

                    b.HasIndex("FechadoPorId")
                        .HasDatabaseName("ix_fechamentos_dia_fechado_por_id");

                    b.HasIndex("ReabertoPorId")
                        .HasDatabaseName("ix_fechamentos_dia_reaberto_por_id");

                    b.HasIndex("TenantId", "Data", "EquipeId")
                        .IsUnique()
                        .HasDatabaseName("ix_fechamentos_dia_tenant_id_data_equipe_id");

                    b.ToTable("fechamentos_dia", (string)null);
                });

            modelBuilder.Entity("Premag.Core.Entities.Foto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Altura")
                        .HasColumnType("integer")
                        .HasColumnName("altura");

                    b.Property<Guid?>("ApontamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("apontamento_id");

                    b.Property<int>("Bytes")
                        .HasColumnType("integer")
                        .HasColumnName("bytes");

                    b.Property<DateTimeOffset>("CapturadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("capturada_em");

                    b.Property<Guid>("ClienteUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_uuid");

                    b.Property<Guid?>("ColaboradorId")
                        .HasColumnType("uuid")
                        .HasColumnName("colaborador_id");

                    b.Property<Guid>("EnviadaPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("enviada_por_id");

                    b.Property<bool>("Excluido")
                        .HasColumnType("boolean")
                        .HasColumnName("excluido");

                    b.Property<DateOnly?>("ExpiraEm")
                        .HasColumnType("date")
                        .HasColumnName("expira_em");

                    b.Property<Guid>("FrenteId")
                        .HasColumnType("uuid")
                        .HasColumnName("frente_id");

                    b.Property<string>("HashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash_sha256");

                    b.Property<int>("Largura")
                        .HasColumnType("integer")
                        .HasColumnName("largura");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("object_key");

                    b.Property<string>("Observacao")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("observacao");

                    b.Property<decimal?>("Quantidade")
                        .HasPrecision(14, 3)
                        .HasColumnType("numeric(14,3)")
                        .HasColumnName("quantidade");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("ThumbKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("thumb_key");

                    b.Property<short>("Tipo")
                        .HasColumnType("smallint")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_fotos");

                    b.HasIndex("ApontamentoId")
                        .HasDatabaseName("ix_fotos_apontamento_id");

                    b.HasIndex("ColaboradorId")
                        .HasDatabaseName("ix_fotos_colaborador_id");

                    b.HasIndex("EnviadaPorId")
                        .HasDatabaseName("ix_fotos_enviada_por_id");

                    b.HasIndex("FrenteId")
                        .HasDatabaseName("ix_fotos_frente_id");

                    b.HasIndex("TenantId", "ClienteUuid")
                        .IsUnique()
                        .HasDatabaseName("ix_fotos_tenant_id_cliente_uuid");

                    b.ToTable("fotos", (string)null);
                });

            modelBuilder.Entity("Premag.Core.Entities.Frente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ativa");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("cor");

                    b.Property<Guid?>("EquipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipe_id");

                    b.Property<Guid>("EtapaId")
                        .HasColumnType("uuid")
                        .HasColumnName("etapa_id");

                    b.Property<decimal?>("HhOrcadoPorUnidade")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("hh_orcado_por_unidade");

                    b.Property<string>("ItemOrcamentoSienge")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("item_orcamento_sienge");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("nome");

                    b.Property<Guid>("ObraId")
                        .HasColumnType("uuid")
                        .HasColumnName("obra_id");

                    b.Property<decimal>("QuantidadeConcluida")
                        .HasPrecision(14, 3)
                        .HasColumnType("numeric(14,3)")
                        .HasColumnName("quantidade_concluida");

                    b.Property<decimal>("QuantidadePrevista")
                        .HasPrecision(14, 3)
                        .HasColumnType("numeric(14,3)")
                        .HasColumnName("quantidade_prevista");

                    b.Property<decimal?>("TaxaAcoKgPorUnidade")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("taxa_aco_kg_por_unidade");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("unidade");

                    b.HasKey("Id")
                        .HasName("pk_frentes");

                    b.HasIndex("EquipeId")
                        .HasDatabaseName("ix_frentes_equipe_id");

                    b.HasIndex("EtapaId")
                        .HasDatabaseName("ix_frentes_etapa_id");

                    b.HasIndex("ObraId")
                        .HasDatabaseName("ix_frentes_obra_id");

                    b.HasIndex("TenantId", "ObraId", "Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_frentes_tenant_id_obra_id_nome");

                    b.ToTable("frentes", (string)null);
                });

            modelBuilder.Entity("Premag.Core.Entities.InscricaoPush", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endpoint");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("p256dh");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UltimoEnvioEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_envio_em");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_inscricoes_push");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_inscricoes_push_usuario_id");

                    b.ToTable("inscricoes_push", (string)null);
                });

            modelBuilder.Entity("Premag.Core.Entities.JornadaDia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ColaboradorId")
                        .HasColumnType("uuid")
                        .HasColumnName("colaborador_id");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<TimeOnly?>("Entrada")
                        .HasColumnType("time without time zone")
                        .HasColumnName("entrada");

                    b.Property<DateTimeOffset>("ImportadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("importado_em");

                    b.Property<int>("IntervaloMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("intervalo_minutos");

                    b.Property<int>("MinutosApurados")
                        .HasColumnType("integer")
                        .HasColumnName("minutos_apurados");

                    b.Property<short>("Origem")
                        .HasColumnType("smallint")
                        .HasColumnName("origem");

                    b.Property<TimeOnly?>("Saida")
                        .HasColumnType("time without time zone")
                        .HasColumnName("saida");

                    b.Property<short>("Situacao")
                        .HasColumnType("smallint")
                        .HasColumnName("situacao");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_jornadas_dia");

                    b.HasIndex("ColaboradorId")
                        .HasDatabaseName("ix_jornadas_dia_colaborador_id");

                    b.HasIndex("TenantId", "ColaboradorId", "Data")
                        .IsUnique()
                        .HasDatabaseName("ix_jornadas_dia_tenant_id_colaborador_id_data");

                    b.ToTable("jornadas_dia", (string)null);
                });

            modelBuilder.Entity("Premag.Core.Entities.LoteSincronizacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DispositivoId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("dispositivo_id");

                    b.Property<int>("ItensAceitos")
                        .HasColumnType("integer")
                        .HasColumnName("itens_aceitos");

                    b.Property<int>("ItensRecebidos")
                        .HasColumnType("integer")
                        .HasColumnName("itens_recebidos");

                    b.Property<int>("ItensRejeitados")
                        .HasColumnType("integer")
                        .HasColumnName("itens_rejeitados");

                    b.Property<int>("PayloadBytes")
                        .HasColumnType("integer")
                        .HasColumnName("payload_bytes");

                    b.Property<DateTimeOffset>("RecebidoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recebido_em");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_lotes_sincronizacao");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_lotes_sincronizacao_usuario_id");

                    b.ToTable("lotes_sincronizacao", (string)null);
                });

            modelBuilder.Entity("Premag.Core.Entities.MotivoParada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("ExigeObservacao")
                        .HasColumnType("boolean")
                        .HasColumnName("exige_observacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nome");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_motivos_parada");

                    b.HasIndex("TenantId", "Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_motivos_parada_tenant_id_nome");

                    b.ToTable("motivos_parada", (string)null);
                });

            modelBuilder.Entity("Premag.Core.Entities.Obra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CentroCusto")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("centro_custo");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("cliente");

                    b.Property<string>("CodigoSienge")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("codigo_sienge");

                    b.Property<DateOnly?>("DataInicio")
                        .HasColumnType("date")
                        .HasColumnName("data_inicio");

                    b.Property<DateOnly?>("DataPrevistaFim")
                        .HasColumnType("date")
                        .HasColumnName("data_prevista_fim");

                    b.Property<bool>("Interna")
                        .HasColumnType("boolean")
                        .HasColumnName("interna");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("local");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("nome");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_obras");

                    b.ToTable("obras", (string)null);
                });

            modelBuilder.Entity("Premag.Core.Entities.Ocorrencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApontamentoGeradoId")
                        .HasColumnType("uuid")
                        .HasColumnName("apontamento_gerado_id");

                    b.Property<Guid?>("ColaboradorId")
                        .HasColumnType("uuid")
                        .HasColumnName("colaborador_id");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<DateTimeOffset>("DetectadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detectada_em");

                    b.Property<Guid?>("EquipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipe_id");

                    b.Property<Guid?>("FrenteId")
                        .HasColumnType("uuid")
                        .HasColumnName("frente_id");

                    b.Property<TimeOnly?>("JanelaInicio")
                        .HasColumnType("time without time zone")
                        .HasColumnName("janela_inicio");

                    b.Property<string>("Justificativa")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("justificativa");

                    b.Property<int?>("MinutosDecorridos")
                        .HasColumnType("integer")
                        .HasColumnName("minutos_decorridos");

                    b.Property<DateTimeOffset?>("NotificadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("notificada_em");

                    b.Property<DateTimeOffset?>("ReconhecidaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reconhecida_em");

                    b.Property<Guid?>("ReconhecidaPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("reconhecida_por_id");

                    b.Property<short>("Severidade")
                        .HasColumnType("smallint")
                        .HasColumnName("severidade");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<short>("Tipo")
                        .HasColumnType("smallint")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_ocorrencias");

                    b.HasIndex("ApontamentoGeradoId")
                        .HasDatabaseName("ix_ocorrencias_apontamento_gerado_id");

                    b.HasIndex("ColaboradorId")
                        .HasDatabaseName("ix_ocorrencias_colaborador_id");

                    b.HasIndex("EquipeId")
                        .HasDatabaseName("ix_ocorrencias_equipe_id");

                    b.HasIndex("FrenteId")
                        .HasDatabaseName("ix_ocorrencias_frente_id");

                    b.HasIndex("ReconhecidaPorId")
                        .HasDatabaseName("ix_ocorrencias_reconhecida_por_id");

                    b.HasIndex("TenantId", "Tipo", "ColaboradorId", "Data", "JanelaInicio")
                        .IsUnique()
                        .HasDatabaseName("ix_ocorrencias_dedup");

                    b.ToTable("ocorrencias", (string)null);
                });

            modelBuilder.Entity("Premag.Core.Entities.Producao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApontamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("apontamento_id");

                    b.Property<Guid>("ClienteUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_uuid");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<bool>("Excluido")
                        .HasColumnType("boolean")
                        .HasColumnName("excluido");

                    b.Property<Guid?>("FotoId")
                        .HasColumnType("uuid")
                        .HasColumnName("foto_id");

                    b.Property<Guid>("FrenteId")
                        .HasColumnType("uuid")
                        .HasColumnName("frente_id");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(14, 3)
                        .HasColumnType("numeric(14,3)")
                        .HasColumnName("quantidade");

                    b.Property<DateTimeOffset>("RegistradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registrado_em");

                    b.Property<Guid>("RegistradoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("registrado_por_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_producoes");

                    b.HasIndex("ApontamentoId")
                        .HasDatabaseName("ix_producoes_apontamento_id");

                    b.HasIndex("FotoId")
                        .HasDatabaseName("ix_producoes_foto_id");

                    b.HasIndex("FrenteId")
                        .HasDatabaseName("ix_producoes_frente_id");

                    b.HasIndex("RegistradoPorId")
                        .HasDatabaseName("ix_producoes_registrado_por_id");

                    b.HasIndex("TenantId", "ClienteUuid")
                        .IsUnique()
                        .HasDatabaseName("ix_producoes_tenant_id_cliente_uuid");

                    b.HasIndex("TenantId", "FrenteId", "Data")
                        .HasDatabaseName("ix_producoes_tenant_id_frente_id_data");

                    b.ToTable("producoes", (string)null);
                });

            modelBuilder.Entity("Premag.Core.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DispositivoId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("dispositivo_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("token");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_refresh_tokens_tenant_id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_refresh_tokens_usuario_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Premag.Core.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_slug");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Premag.Core.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<Guid?>("ColaboradorId")
                        .HasColumnType("uuid")
                        .HasColumnName("colaborador_id");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Email")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("email");

                    b.Property<Guid?>("EquipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipe_id");

                    b.Property<string>("NomeExibicao")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome_exibicao");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("perfil");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("senha_hash");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UltimoAcesso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_acesso");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("ColaboradorId")
                        .HasDatabaseName("ix_usuarios_colaborador_id");

                    b.HasIndex("EquipeId")
                        .HasDatabaseName("ix_usuarios_equipe_id");

                    b.HasIndex("TenantId", "UserName")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_tenant_id_user_name");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Premag.Core.Entities.Apontamento", b =>
                {
                    b.HasOne("Premag.Core.Entities.Usuario", "AlteradoPor")
                        .WithMany()
                        .HasForeignKey("AlteradoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_apontamentos_users_alterado_por_id");

                    b.HasOne("Premag.Core.Entities.Colaborador", "Colaborador")
                        .WithMany()
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_apontamentos_colaboradores_colaborador_id");

                    b.HasOne("Premag.Core.Entities.Usuario", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_apontamentos_users_criado_por_id");

                    b.HasOne("Premag.Core.Entities.Frente", "Frente")
                        .WithMany()
                        .HasForeignKey("FrenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_apontamentos_frentes_frente_id");

                    b.HasOne("Premag.Core.Entities.MotivoParada", "MotivoParada")
                        .WithMany()
                        .HasForeignKey("MotivoParadaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_apontamentos_motivos_parada_motivo_parada_id");

                    b.Navigation("AlteradoPor");

                    b.Navigation("Colaborador");

                    b.Navigation("CriadoPor");

                    b.Navigation("Frente");

                    b.Navigation("MotivoParada");
                });

            modelBuilder.Entity("Premag.Core.Entities.Colaborador", b =>
                {
                    b.HasOne("Premag.Core.Entities.Equipe", "Equipe")
                        .WithMany("Colaboradores")
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_colaboradores_equipes_equipe_id");

                    b.Navigation("Equipe");
                });

            modelBuilder.Entity("Premag.Core.Entities.Equipe", b =>
                {
                    b.HasOne("Premag.Core.Entities.Usuario", "Encarregado")
                        .WithMany()
                        .HasForeignKey("EncarregadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_equipes_usuarios_encarregado_id");

                    b.Navigation("Encarregado");
                });

            modelBuilder.Entity("Premag.Core.Entities.FechamentoDia", b =>
                {
                    b.HasOne("Premag.Core.Entities.Equipe", "Equipe")
                        .WithMany()
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_fechamentos_dia_equipes_equipe_id");

                    b.HasOne("Premag.Core.Entities.Usuario", "FechadoPor")
                        .WithMany()
                        .HasForeignKey("FechadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fechamentos_dia_users_fechado_por_id");

                    b.HasOne("Premag.Core.Entities.Usuario", "ReabertoPor")
                        .WithMany()
                        .HasForeignKey("ReabertoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_fechamentos_dia_users_reaberto_por_id");

                    b.Navigation("Equipe");

                    b.Navigation("FechadoPor");

                    b.Navigation("ReabertoPor");
                });

            modelBuilder.Entity("Premag.Core.Entities.Foto", b =>
                {
                    b.HasOne("Premag.Core.Entities.Apontamento", "Apontamento")
                        .WithMany()
                        .HasForeignKey("ApontamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_fotos_apontamentos_apontamento_id");

                    b.HasOne("Premag.Core.Entities.Colaborador", "Colaborador")
                        .WithMany()
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_fotos_colaboradores_colaborador_id");

                    b.HasOne("Premag.Core.Entities.Usuario", "EnviadaPor")
                        .WithMany()
                        .HasForeignKey("EnviadaPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fotos_users_enviada_por_id");

                    b.HasOne("Premag.Core.Entities.Frente", "Frente")
                        .WithMany()
                        .HasForeignKey("FrenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fotos_frentes_frente_id");

                    b.Navigation("Apontamento");

                    b.Navigation("Colaborador");

                    b.Navigation("EnviadaPor");

                    b.Navigation("Frente");
                });

            modelBuilder.Entity("Premag.Core.Entities.Frente", b =>
                {
                    b.HasOne("Premag.Core.Entities.Equipe", "Equipe")
                        .WithMany()
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_frentes_equipes_equipe_id");

                    b.HasOne("Premag.Core.Entities.Etapa", "Etapa")
                        .WithMany()
                        .HasForeignKey("EtapaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_frentes_etapas_etapa_id");

                    b.HasOne("Premag.Core.Entities.Obra", "Obra")
                        .WithMany("Frentes")
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_frentes_obras_obra_id");

                    b.Navigation("Equipe");

                    b.Navigation("Etapa");

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("Premag.Core.Entities.InscricaoPush", b =>
                {
                    b.HasOne("Premag.Core.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inscricoes_push_users_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Premag.Core.Entities.JornadaDia", b =>
                {
                    b.HasOne("Premag.Core.Entities.Colaborador", "Colaborador")
                        .WithMany()
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_jornadas_dia_colaboradores_colaborador_id");

                    b.Navigation("Colaborador");
                });

            modelBuilder.Entity("Premag.Core.Entities.LoteSincronizacao", b =>
                {
                    b.HasOne("Premag.Core.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lotes_sincronizacao_users_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Premag.Core.Entities.Ocorrencia", b =>
                {
                    b.HasOne("Premag.Core.Entities.Apontamento", "ApontamentoGerado")
                        .WithMany()
                        .HasForeignKey("ApontamentoGeradoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ocorrencias_apontamentos_apontamento_gerado_id");

                    b.HasOne("Premag.Core.Entities.Colaborador", "Colaborador")
                        .WithMany()
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ocorrencias_colaboradores_colaborador_id");

                    b.HasOne("Premag.Core.Entities.Equipe", "Equipe")
                        .WithMany()
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ocorrencias_equipes_equipe_id");

                    b.HasOne("Premag.Core.Entities.Frente", "Frente")
                        .WithMany()
                        .HasForeignKey("FrenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ocorrencias_frentes_frente_id");

                    b.HasOne("Premag.Core.Entities.Usuario", "ReconhecidaPor")
                        .WithMany()
                        .HasForeignKey("ReconhecidaPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ocorrencias_users_reconhecida_por_id");

                    b.Navigation("ApontamentoGerado");

                    b.Navigation("Colaborador");

                    b.Navigation("Equipe");

                    b.Navigation("Frente");

                    b.Navigation("ReconhecidaPor");
                });

            modelBuilder.Entity("Premag.Core.Entities.Producao", b =>
                {
                    b.HasOne("Premag.Core.Entities.Apontamento", "Apontamento")
                        .WithMany()
                        .HasForeignKey("ApontamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_producoes_apontamentos_apontamento_id");

                    b.HasOne("Premag.Core.Entities.Foto", "Foto")
                        .WithMany()
                        .HasForeignKey("FotoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_producoes_fotos_foto_id");

                    b.HasOne("Premag.Core.Entities.Frente", "Frente")
                        .WithMany()
                        .HasForeignKey("FrenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_producoes_frentes_frente_id");

                    b.HasOne("Premag.Core.Entities.Usuario", "RegistradoPor")
                        .WithMany()
                        .HasForeignKey("RegistradoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_producoes_users_registrado_por_id");

                    b.Navigation("Apontamento");

                    b.Navigation("Foto");

                    b.Navigation("Frente");

                    b.Navigation("RegistradoPor");
                });

            modelBuilder.Entity("Premag.Core.Entities.RefreshToken", b =>
                {
                    b.HasOne("Premag.Core.Entities.Usuario", "Usuario")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Premag.Core.Entities.Usuario", b =>
                {
                    b.HasOne("Premag.Core.Entities.Colaborador", "Colaborador")
                        .WithMany()
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_usuarios_colaboradores_colaborador_id");

                    b.HasOne("Premag.Core.Entities.Equipe", "Equipe")
                        .WithMany()
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_usuarios_equipes_equipe_id");

                    b.Navigation("Colaborador");

                    b.Navigation("Equipe");
                });

            modelBuilder.Entity("Premag.Core.Entities.Equipe", b =>
                {
                    b.Navigation("Colaboradores");
                });

            modelBuilder.Entity("Premag.Core.Entities.Obra", b =>
                {
                    b.Navigation("Frentes");
                });

            modelBuilder.Entity("Premag.Core.Entities.Usuario", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
